[workspace]
resolver = "3"
members = [
  "shgen",
  "shgen-config-fs",
  "shgen-config-model",
  "shgen-core",
  "shgen-keep-awake",
  "shgen-keys",
  "shweb",
]

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
ed25519-dalek = { version = "3.0.0-pre.1", default-features = false }
rand = "0.9.2"
rand_chacha = "0.9.0"
serde = "1.0.228"

[profile.release]
lto = "thin"
codegen-units = 1
