[package]
name = "shgen-config-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
shgen-config-core = { path = "../shgen-config-core" }
wasm-bindgen.workspace = true
