[package]
name = "shgen-config-model"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
shgen-core = { path = "../shgen-core" }

[features]
default = []
wasm-js = []
